import omni.replicator.core as rep
import json

# 1. Define the Scene and Assets
# This would load the OpenUSD file generated by the SRA in Blender
SCENE_PATH = "scenes/soccer_field.usd"

# Load the SRA Personality Vector (Custom Context)
with open("sra-cinematography-style.json", "r") as f:
    personality = json.load(f)
shake = personality["camera_shake"]
jitter_min = shake["position_jitter_min"]
jitter_max = shake["position_jitter_max"]
rot_min = tuple(shake["rotation_min"])
rot_max = tuple(shake["rotation_max"])

with rep.new_layer():
    # Load the soccer field environment
    field = rep.create.from_usd(SCENE_PATH)
    
    # 2. Define the Virtual Camera
    # This represents the user's smartphone in the GalaSpo rec app
    camera = rep.create.camera(position=(0, 150, 500), look_at=(0, 0, 0))
    
    # 3. Define Render Products (The Video Feed)
    render_product = rep.create.render_product(camera, resolution=(1920, 1080))
    
    # 4. Sensor Simulation: Animate Camera & Capture IMU/Gyro
    # We simulate a "handheld" walk along the sideline using the human-defined personality vector
    def get_camera_path():
        with rep.trigger.on_frame(num_frames=300):
            # Move camera from x=-500 to x=500 over 300 frames
            # Apply the custom shake math defined by the human SRA
            rep.modify.pose(
                camera,
                position=rep.distribution.sequence([
                    (x, 150 + rep.distribution.uniform(jitter_min, jitter_max).sample(), 500) 
                    for x in range(-500, 501, 3)
                ]),
                rotation=rep.distribution.uniform(rot_min, rot_max)
            )
        return camera

    get_camera_path()

    # 5. Initialize the Data Writer
    # This writer exports the Video, Bounding Boxes for players, 
    # and the NATIVE IMU/Gyro stream.
    writer = rep.WriterRegistry.get("BasicWriter")
    writer.initialize(
        output_dir="output/session_001",
        rgb=True,
        bounding_box_2d_tight=True,  # To verify the player detection Neural Engine
        camera_params=True           # Exports the IMU/Gyro/Rotation metadata JSON
    )
    
    writer.attach([render_product])

    # 6. Execute the Generation
    # This runs headlessly on the AI Rack (RTX 5090)
    rep.orchestrator.run()

print("✅ SRT Generation Complete. Synchronized Video and Gyro data exported to output/session_001")
